/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponsePublicTag } from '../../models/api-response-public-tag';

export interface GetTag$Params {

/**
 * 標籤 ID
 */
  id: string;
}

export function getTag(http: HttpClient, rootUrl: string, params: GetTag$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponsePublicTag>> {
  const rb = new RequestBuilder(rootUrl, getTag.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponsePublicTag>;
    })
  );
}

getTag.PATH = '/public/tags/{id}';
