/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedResponsePublicTagListItem } from '../../models/paginated-response-public-tag-list-item';

export interface GetTags$Params {

/**
 * 頁碼（從 1 開始）
 */
  page?: number;

/**
 * 每頁筆數
 */
  pageSize?: number;
}

export function getTags(http: HttpClient, rootUrl: string, params?: GetTags$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedResponsePublicTagListItem>> {
  const rb = new RequestBuilder(rootUrl, getTags.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('pageSize', params.pageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedResponsePublicTagListItem>;
    })
  );
}

getTags.PATH = '/public/tags';
