/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseTopic } from '../../models/api-response-topic';
import { CreateTopicDto } from '../../models/create-topic-dto';

export interface CreateTopic$Params {
      body: CreateTopicDto
}

export function createTopic(http: HttpClient, rootUrl: string, params: CreateTopic$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseTopic>> {
  const rb = new RequestBuilder(rootUrl, createTopic.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseTopic>;
    })
  );
}

createTopic.PATH = '/admin/topics';
