/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseTopic } from '../../models/api-response-topic';
import { UpdateTopicDto } from '../../models/update-topic-dto';

export interface UpdateTopic$Params {

/**
 * 主題 slug
 */
  id: string;
      body: UpdateTopicDto
}

export function updateTopic(http: HttpClient, rootUrl: string, params: UpdateTopic$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseTopic>> {
  const rb = new RequestBuilder(rootUrl, updateTopic.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseTopic>;
    })
  );
}

updateTopic.PATH = '/admin/topics/{id}';
