/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseBannerOrUndefined } from '../../models/api-response-banner-or-undefined';

export interface GetPublicBanner$Params {
}

export function getPublicBanner(http: HttpClient, rootUrl: string, params?: GetPublicBanner$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseBannerOrUndefined>> {
  const rb = new RequestBuilder(rootUrl, getPublicBanner.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseBannerOrUndefined>;
    })
  );
}

getPublicBanner.PATH = '/public/banner';
