/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponsePostLatestItemArray } from '../../models/api-response-post-latest-item-array';

export interface GetLatestPosts$Params {
}

export function getLatestPosts(http: HttpClient, rootUrl: string, params?: GetLatestPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponsePostLatestItemArray>> {
  const rb = new RequestBuilder(rootUrl, getLatestPosts.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponsePostLatestItemArray>;
    })
  );
}

getLatestPosts.PATH = '/public/posts/latest';
