/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponsePublicPost } from '../../models/api-response-public-post';

export interface GetPost$Params {

/**
 * 文章 ID
 */
  id: string;
}

export function getPost(http: HttpClient, rootUrl: string, params: GetPost$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponsePublicPost>> {
  const rb = new RequestBuilder(rootUrl, getPost.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponsePublicPost>;
    })
  );
}

getPost.PATH = '/public/posts/{id}';
