/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseBannerModel } from '../../models/api-response-banner-model';
import { CreateBannerDto } from '../../models/create-banner-dto';

export interface CreateBanner$Params {
      body: CreateBannerDto
}

export function createBanner(http: HttpClient, rootUrl: string, params: CreateBanner$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseBannerModel>> {
  const rb = new RequestBuilder(rootUrl, createBanner.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseBannerModel>;
    })
  );
}

createBanner.PATH = '/admin/banner';
