/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseBannerModelArray } from '../../models/api-response-banner-model-array';

export interface GetBanners$Params {
}

export function getBanners(http: HttpClient, rootUrl: string, params?: GetBanners$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseBannerModelArray>> {
  const rb = new RequestBuilder(rootUrl, getBanners.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseBannerModelArray>;
    })
  );
}

getBanners.PATH = '/admin/banner';
