/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseBannerModel } from '../../models/api-response-banner-model';

export interface GetBanner$Params {

/**
 * banner ID
 */
  id: string;
}

export function getBanner(http: HttpClient, rootUrl: string, params: GetBanner$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseBannerModel>> {
  const rb = new RequestBuilder(rootUrl, getBanner.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseBannerModel>;
    })
  );
}

getBanner.PATH = '/admin/banner/{id}';
