/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseBannerModel } from '../../models/api-response-banner-model';
import { UpdateBannerDto } from '../../models/update-banner-dto';

export interface UpdateBanner$Params {

/**
 * banner ID
 */
  id: string;
      body: UpdateBannerDto
}

export function updateBanner(http: HttpClient, rootUrl: string, params: UpdateBanner$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseBannerModel>> {
  const rb = new RequestBuilder(rootUrl, updateBanner.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseBannerModel>;
    })
  );
}

updateBanner.PATH = '/admin/banner/{id}';
