/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseTagArray } from '../../models/api-response-tag-array';

export interface GetTags_1$Params {
}

export function getTags_1(http: HttpClient, rootUrl: string, params?: GetTags_1$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseTagArray>> {
  const rb = new RequestBuilder(rootUrl, getTags_1.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseTagArray>;
    })
  );
}

getTags_1.PATH = '/admin/tags';
