/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaginatedResponsePublicTopicSummary } from '../../models/paginated-response-public-topic-summary';

export interface GetTopics$Params {
  page?: number;
  pageSize?: number;
}

export function getTopics(http: HttpClient, rootUrl: string, params?: GetTopics$Params, context?: HttpContext): Observable<StrictHttpResponse<PaginatedResponsePublicTopicSummary>> {
  const rb = new RequestBuilder(rootUrl, getTopics.PATH, 'get');
  if (params) {
    if (params.page !== undefined) {
      rb.query('page', params.page, {});
    }
    if (params.pageSize !== undefined) {
      rb.query('pageSize', params.pageSize, {});
    }
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaginatedResponsePublicTopicSummary>;
    })
  );
}

getTopics.PATH = '/public/topics';
