/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponseCleanupResult } from '../../models/api-response-cleanup-result';

export interface CleanupOrphanImages$Params {
}

export function cleanupOrphanImages(http: HttpClient, rootUrl: string, params?: CleanupOrphanImages$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponseCleanupResult>> {
  const rb = new RequestBuilder(rootUrl, cleanupOrphanImages.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponseCleanupResult>;
    })
  );
}

cleanupOrphanImages.PATH = '/admin/upload/cleanup';
