/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicTopic } from '../models/public-topic';

/**
 * 統一 API 回傳格式
 */
export interface ApiResponsePublicTopic {
  data: PublicTopic;
}
