/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TopicNavSection } from '../models/topic-nav-section';

/**
 * 統一 API 回傳格式
 */
export interface ApiResponseTopicNavSectionArray {
  data: Array<TopicNavSection>;
}
