/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicBanner } from '../models/public-banner';

/**
 * 統一 API 回傳格式
 */
export interface ApiResponsePublicBannerOrUndefined {
  data?: PublicBanner;
}
