/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Banner } from '../models/banner';

/**
 * 統一 API 回傳格式
 */
export interface ApiResponseBannerOrUndefined {
  data?: Banner;
}
