/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicPost } from '../models/public-post';

/**
 * 統一 API 回傳格式
 */
export interface ApiResponsePublicPost {
  data: PublicPost;
}
