/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicTag } from '../models/public-tag';

/**
 * 統一 API 回傳格式
 */
export interface ApiResponsePublicTagArray {
  data: Array<PublicTag>;
}
