/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PostModel } from '../models/post-model';

/**
 * 統一 API 回傳格式
 */
export interface ApiResponsePostModelArray {
  data: Array<PostModel>;
}
