/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PostLatestItem } from '../models/post-latest-item';

/**
 * 統一 API 回傳格式
 */
export interface ApiResponsePostLatestItemArray {
  data: Array<PostLatestItem>;
}
