/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TopicWithSections } from '../models/topic-with-sections';

/**
 * 統一 API 回傳格式
 */
export interface ApiResponseTopicWithSections {
  data: TopicWithSections;
}
