/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BannerModel } from '../models/banner-model';

/**
 * 統一 API 回傳格式
 */
export interface ApiResponseBannerModelArray {
  data: Array<BannerModel>;
}
