/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TopicNavSection } from './topic-nav-section';

export interface ApiResponseTopicNavSectionArray {
  data: TopicNavSection[];
}
