/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BannerType } from './banner-type';

/**
 * Each possible value of `BannerType`
 */
export const BANNER_TYPE: BannerType[] = [
  'img',
  'imgText'
];