/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BannerModel {

  /**
   * 內容
   */
  content: string | null;

  /**
   * 建立時間（UTC）
   */
  createdAt: string;

  /**
   * 唯一識別碼（UUID，由後端自動產生）
   */
  id: string;

  /**
   * 圖片替代文字
   */
  imgAlt: string;

  /**
   * 圖片網址
   */
  imgUrl: string;

  /**
   * 是否啟用
   */
  isActive: boolean;

  /**
   * banner 名稱
   */
  title: string;

  /**
   * banner 類型
   */
  type: string;

  /**
   * 最後更新時間（UTC），未更新過則為 null
   */
  updatedAt: string;
}
