/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriesType } from './categories-type';

/**
 * Each possible value of `CategoriesType`
 */
export const CATEGORIES_TYPE: CategoriesType[] = [
  'tech',
  'life'
];