/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 新增主題時的請求資料
 */
export interface CreateTopicDto {

  /**
   * 主題簡介
   */
  description?: string;

  /**
   * 主題名稱（必填）
   */
  name: string;
}
