/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 新增文章時的請求資料（id 和時間戳由後端自動產生）
 */
export interface CreatePostDto {

  /**
   * 作者名稱（必填）
   */
  author: string;

  /**
   * 文章內文（必填）
   */
  content: string;

  /**
   * 文章標題（必填）
   */
  title: string;
}
