/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BannerType } from '../models/banner-type';
export interface CreateBannerDto {

  /**
   * 內容
   */
  content?: string;

  /**
   * 圖片網址
   */
  img: string;

  /**
   * banner 名稱
   */
  title: string;

  /**
   * banner 類型
   */
  type: BannerType;
}
