/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriesType } from '../models/categories-type';
import { PostStatus } from '../models/post-status';

/**
 * 新增文章時的請求資料
 */
export interface CreatePostDto {

  /**
   * 文章分類（必填）
   */
  categories: CategoriesType;

  /**
   * 文章內文（必填）
   */
  content: string;

  /**
   * 發布狀態，不傳預設為 draft
   */
  status?: PostStatus;

  /**
   * 標籤名稱清單，tag 不存在時自動建立
   */
  tags?: Array<string>;

  /**
   * 文章標題（必填）
   */
  title: string;

  /**
   * 所屬主題 ID
   */
  topicId?: string;
}
