/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicTagListItem } from '../models/public-tag-list-item';

/**
 * 分頁 API 回傳格式
 */
export interface PaginatedResponsePublicTagListItem {
  data: Array<PublicTagListItem>;
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}
