/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicTopicSummary } from './public-topic-summary';

export interface PaginatedResponsePublicTopicSummary {
  data: PublicTopicSummary[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}
