/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PostListItem } from '../models/post-list-item';

/**
 * 分頁 API 回傳格式
 */
export interface PaginatedResponsePostListItem {
  data: Array<PostListItem>;
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}
