/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BannerModel } from '../models/banner-model';

/**
 * 分頁 API 回傳格式
 */
export interface PaginatedResponseBannerModel {
  data: Array<BannerModel>;
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}
