/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Topic } from '../models/topic';

/**
 * 分頁 API 回傳格式
 */
export interface PaginatedResponseTopic {
  data: Array<Topic>;
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}
