/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublicTopic } from '../models/public-topic';

/**
 * 分頁 API 回傳格式
 */
export interface PaginatedResponsePublicTopic {
  data: Array<PublicTopic>;
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}
