/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PostStatus } from './post-status';

/**
 * Each possible value of `PostStatus`
 */
export const POST_STATUS: PostStatus[] = [
  'published',
  'draft'
];