/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriesType } from '../models/categories-type';
import { PostStatus } from '../models/post-status';
import { PublicTag } from '../models/public-tag';
import { PublicTopic } from '../models/public-topic';

/**
 * 後台完整文章物件
 */
export interface PostModel {

  /**
   * 文章分類
   */
  categories: CategoriesType;

  /**
   * 文章內文（Markdown）
   */
  content: string;

  /**
   * 建立時間（UTC）
   */
  createdAt: string;

  /**
   * 文章唯一識別碼（UUID）
   */
  id: string;

  /**
   * 發布狀態
   */
  status: PostStatus;

  /**
   * 文章標籤列表
   */
  tags: Array<PublicTag>;

  /**
   * 文章標題
   */
  title: string;

  /**
   * 所屬主題
   */
  topic: PublicTopic | null;

  /**
   * 所屬主題 ID
   */
  topicId: string | null;

  /**
   * 在章節內的排序
   */
  topicOrder: number | null;

  /**
   * 所屬章節 ID
   */
  topicSectionId: string | null;

  /**
   * 最後更新時間（UTC）
   */
  updatedAt: string;
}
