/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 後台完整文章物件（從資料庫/記憶體讀出來的完整資料）
 */
export interface PostModel {

  /**
   * 作者名稱
   */
  author: string;

  /**
   * 文章內文（支援純文字或 Markdown）
   */
  content: string;

  /**
   * 建立時間（UTC）
   */
  createdAt: string;

  /**
   * 文章唯一識別碼（UUID，由後端自動產生）
   */
  id: string;

  /**
   * 文章標題
   */
  title: string;

  /**
   * 最後更新時間（UTC），未更新過則為 null
   */
  updatedAt: string;
}
