/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriesType } from '../models/categories-type';
import { PublicTag } from '../models/public-tag';

/**
 * 首頁最新文章項目（含 tags 和截斷的 content）
 */
export interface PostLatestItem {

  /**
   * 文章分類
   */
  categories: CategoriesType;

  /**
   * 文章內文前 100 字
   */
  content: string;

  /**
   * 建立時間（UTC）
   */
  createdAt: string;

  /**
   * 文章唯一識別碼
   */
  id: string;

  /**
   * 文章標籤列表
   */
  tags: Array<PublicTag>;

  /**
   * 文章標題
   */
  title: string;
}
