/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 前台公開文章物件（不含後台管理欄位）
 */
export interface PublicPost {

  /**
   * 作者名稱
   */
  author: string;

  /**
   * 文章內文
   */
  content: string;

  /**
   * 建立時間（UTC）
   */
  createdAt: string;

  /**
   * 文章唯一識別碼（UUID）
   */
  id: string;

  /**
   * 文章標題
   */
  title: string;
}
