/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 前台公開主題物件
 */
export interface PublicTopic {

  /**
   * 主題簡介
   */
  description: string | null;

  /**
   * 主題 slug
   */
  id: string;

  /**
   * 主題名稱
   */
  name: string;
}
