/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BannerType } from '../models/banner-type';

/**
 * 前台公開 banner 物件（不含後台管理欄位）
 */
export interface PublicBanner {

  /**
   * 內容
   */
  content: string | null;

  /**
   * 唯一識別碼（UUID，由後端自動產生）
   */
  id: string;

  /**
   * 圖片替代文字
   */
  imgAlt: string;

  /**
   * 圖片網址
   */
  imgUrl: string;

  /**
   * banner 名稱
   */
  title: string;

  /**
   * banner 類型
   */
  type: BannerType;
}
