/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicTag {
  id: string;
  name: string;
}

export interface PublicPost {
  id: string;
  title: string;
  content: string;
  categories: string;
  topicId: string | null;
  createdAt: string;
  tags: PublicTag[];
}
