/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 前台標籤列表項目（含文章數，標籤列表頁用）
 */
export interface PublicTagListItem {

  /**
   * 標籤 slug（前端當作路由使用）
   */
  id: string;

  /**
   * 標籤名稱
   */
  name: string;

  /**
   * 使用此標籤的文章數
   */
  postCount: number;
}
