/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 同步主題章節時單一章節的資料
 */
export interface SyncSectionItem {

  /**
   * 現有章節的 UUID，null 表示新增
   */
  id?: string;

  /**
   * 章節名稱
   */
  name: string;

  /**
   * 章節排序
   */
  order: number;

  /**
   * 此章節下的文章 UUID 列表（依排序）
   */
  postIds: Array<string>;
}
