/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SyncSectionItem } from '../models/sync-section-item';

/**
 * 同步主題章節的請求資料
 */
export interface SyncSectionsDto {

  /**
   * 章節列表（完整替換現有章節狀態）
   */
  sections: Array<SyncSectionItem>;
}
