/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 後台完整標籤物件
 */
export interface Tag {

  /**
   * 建立時間（UTC）
   */
  createdAt: string;

  /**
   * 標籤唯一識別碼（UUID，由後端自動產生）
   */
  id: string;

  /**
   * 標籤名稱
   */
  name: string;
}
