/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TopicSectionPost } from '../models/topic-section-post';

/**
 * 後台主題章節物件
 */
export interface TopicSection {

  /**
   * 章節 UUID
   */
  id: string;

  /**
   * 章節名稱
   */
  name: string;

  /**
   * 章節排序
   */
  order: number;

  /**
   * 此章節下的文章列表（依 order 排序）
   */
  posts: Array<TopicSectionPost>;
}
