/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 前台主題 nav 單篇文章
 */
export interface TopicNavPost {

  /**
   * 文章 UUID
   */
  id: string;

  /**
   * 文章標題
   */
  name: string;
}
