/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 後台完整主題物件
 */
export interface Topic {

  /**
   * 建立時間（UTC）
   */
  createdAt: string;

  /**
   * 主題簡介
   */
  description: string | null;

  /**
   * 主題 slug
   */
  id: string;

  /**
   * 主題名稱
   */
  name: string;

  /**
   * 此主題下的文章數
   */
  postCount: number;

  /**
   * 最後更新時間（UTC）
   */
  updatedAt: string;
}
