/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TopicNavItem } from './topic-nav-item';

export interface TopicNavSection {
  id: string;
  name: string;
  items: TopicNavItem[];
}
