/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TopicSection } from '../models/topic-section';

/**
 * 後台主題詳情（含章節與文章）
 */
export interface TopicWithSections {

  /**
   * 建立時間（UTC）
   */
  createdAt: string;

  /**
   * 主題簡介
   */
  description: string | null;

  /**
   * 主題 slug
   */
  id: string;

  /**
   * 主題名稱
   */
  name: string;

  /**
   * 此主題下的文章數
   */
  postCount: number;

  /**
   * 章節列表（依 order 排序）
   */
  sections: Array<TopicSection>;

  /**
   * 最後更新時間（UTC）
   */
  updatedAt: string;
}
