/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TopicNavPost } from '../models/topic-nav-post';

/**
 * 前台主題 nav 章節
 */
export interface TopicNavSection {

  /**
   * 章節 UUID
   */
  id: string;

  /**
   * 此章節下的文章
   */
  items: Array<TopicNavPost>;

  /**
   * 章節名稱
   */
  name: string;
}
