/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 章節內的文章摘要（用於後台主題詳情）
 */
export interface TopicSectionPost {

  /**
   * 文章 UUID
   */
  id: string;

  /**
   * 在章節內的排序
   */
  order: number;

  /**
   * 文章標題
   */
  title: string;
}
