/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 更新文章時的請求資料（所有欄位皆為選填，只傳要改的欄位即可）
 */
export interface UpdatePostDto {

  /**
   * 新的作者名稱
   */
  author?: string;

  /**
   * 新的文章內文
   */
  content?: string;

  /**
   * 新的文章標題
   */
  title?: string;
}
