/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CategoriesType } from '../models/categories-type';
import { PostStatus } from '../models/post-status';

/**
 * 更新文章時的請求資料（所有欄位皆為選填）
 */
export interface UpdatePostDto {

  /**
   * 文章分類
   */
  categories?: CategoriesType;

  /**
   * 新的文章內文
   */
  content?: string;

  /**
   * 發布狀態
   */
  status?: PostStatus;

  /**
   * 傳入則完整替換文章的 tag 列表
   */
  tags?: Array<string>;

  /**
   * 新的文章標題
   */
  title?: string;

  /**
   * 所屬主題 ID（傳 null 可解除關聯）
   */
  topicId?: string | null;
}
