/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateBannerDto {

  /**
   * 內容
   */
  content?: string;

  /**
   * 圖片網址
   */
  img?: string;

  /**
   * 是否啟用
   */
  isActive?: boolean;

  /**
   * banner 名稱
   */
  title?: string;
}
