/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * 更新主題時的請求資料
 */
export interface UpdateTopicDto {

  /**
   * 主題簡介
   */
  description?: string;

  /**
   * 主題名稱
   */
  name?: string;
}
