/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponsePostModel } from '../../models/api-response-post-model';

export interface GetPost_1$Params {

/**
 * 文章 ID
 */
  id: string;
}

export function getPost_1(http: HttpClient, rootUrl: string, params: GetPost_1$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponsePostModel>> {
  const rb = new RequestBuilder(rootUrl, getPost_1.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponsePostModel>;
    })
  );
}

getPost_1.PATH = '/admin/posts/{id}';
