/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiResponsePostModelArray } from '../../models/api-response-post-model-array';

export interface GetPosts_1$Params {
}

export function getPosts_1(http: HttpClient, rootUrl: string, params?: GetPosts_1$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiResponsePostModelArray>> {
  const rb = new RequestBuilder(rootUrl, getPosts_1.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiResponsePostModelArray>;
    })
  );
}

getPosts_1.PATH = '/admin/posts';
